Traceback (most recent call last):
  File "/proj/berzelius-2024-336/users/x_tuhan/garage/quantizedSAE/ternary_sae/ternary_sae.py", line 112, in <module>
    model = train(dataset, config)
  File "/proj/berzelius-2024-336/users/x_tuhan/garage/quantizedSAE/ternary_sae/ternary_sae.py", line 90, in train
    "loss": total_loss/len(config["batch_size"]),
TypeError: object of type 'int' has no len()
